### ISSUE TITLE
Segfault in remmina-plugin-rdp

### ISSUE THREAD

**Issue by ya-petrov** [FreeRDP/Remmina#1053]
* Ubuntu 16.10, 4.8.0-27-generic x86_64,  Unity 7
* Remmina version: 1.2.0-rcgit-15 (git n/a)
* Connecting to 2008R2, 2012R2
* freerdp version: freerdp-x11 2.0.0~dev201609090916+dfsg-1ubuntu0
* remmina-plugin-rdp   1.2.0~rcgit-15+982+next+201610270632~ubuntu16.10.1     amd64

Hi,
error when I try to connect via RDP:

00:13:10 Notebook-PC remmina[11699]: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
00:13:14 Notebook-PC remmina[11699]: GtkDialog mapped without a transient parent. This is discouraged.
00:13:14 Notebook-PC kernel: remmina[11711]: segfault at a0 ip 00007fedb40da9f9 sp 00007feda6aca760 error 6 in remmina-plugin-rdp.so[7fedb40d2000+14000]

**Comment by CS-JS** [comment]
I've found another segfault, maybe these are connected?

```
[New Thread 0x7fffd7aa2700 (LWP 10394)]
[11:56:23:152] [5360:10394] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - @           WARNING: CERTIFICATE NAME MISMATCH!           @
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - The hostname used for this connection (10.15.24.135:3389) 
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - does not match the name given in the certificate:
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - Common Name (CN):
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] -       CAD-AnZw.hoefer.local
[11:56:23:591] [5360:10394] [ERROR][com.freerdp.crypto] - A valid certificate for the wrong name should NOT be trusted!
[New Thread 0x7fffb77fe700 (LWP 10395)]
[Thread 0x7fffb6ffd700 (LWP 10392) exited]
[12:01:56:836] [5360:10315] [INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
[Thread 0x7fffd4d84700 (LWP 10315) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffb6ffd700 (LWP 10467)]
[12:02:44:391] [5360:10467] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[12:02:48:599] [5360:10467] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x20009]
[12:02:48:599] [5360:10467] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
[Thread 0x7fffb6ffd700 (LWP 10467) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffb5ffb700 (LWP 10470)]
[12:02:59:071] [5360:10470] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[12:03:03:630] [5360:10470] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[Thread 0x7fffb5ffb700 (LWP 10470) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffb5ffb700 (LWP 10479)]
[12:03:43:391] [5360:10479] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[New Thread 0x7fffb57fa700 (LWP 10482)]
[12:03:52:671] [5360:10482] [ERROR][com.freerdp.channels.cliprdr.client] - context->custom not set!
[12:03:52:671] [5360:10482] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_general_capability failed with error 1359!
[12:03:52:671] [5360:10482] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_clip_caps failed with error 1359!
[12:03:52:671] [5360:10482] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!
[Thread 0x7fffb57fa700 (LWP 10482) exited]

(remmina:5360): GLib-GObject-CRITICAL **: g_closure_ref: assertion 'closure->ref_count > 0' failed

(remmina:5360): GLib-GObject-CRITICAL **: g_closure_invoke: assertion 'closure->marshal || real_closure->meta_marshal' failed

(remmina:5360): GLib-GObject-CRITICAL **: g_closure_ref: assertion 'closure->ref_count > 0' failed

(remmina:5360): GLib-GObject-CRITICAL **: g_closure_invoke: assertion 'closure->marshal || real_closure->meta_marshal' failed

Thread 1 "remmina" received signal SIGSEGV, Segmentation fault.
0x00007ffff68f1120 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff68f1120 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff690b9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff690c555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff72048b9 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007ffff71f42d8 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff6f06ac3 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff6f0605a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff6f06400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff6f064ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff6be1cdd in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00000000004185c7 in main (argc=1, argv=0x7fffffffded8) at /build/remmina-kPWHfo/remmina-1.2.0~rcgit/remmina/src/remmina.c:260
(gdb) 
```

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @CS-JS @ya-petrov
