### ISSUE TITLE
Remmina crashes after reconnection attempt after entering wrong password

### ISSUE THREAD

**Issue by wsgcsysadmin** [FreeRDP/Remmina#1054]
I've had this issue for at least a year.

Client:
Ubuntu 16.04 amd64 Unity desktop

remmina                                               1.2.0~rcgit-15+982+next+201610270632~ubuntu14.04.1
remmina-common                                        1.2.0~rcgit-15+982+next+201610270632~ubuntu14.04.1
remmina-plugin-rdp                                    1.2.0~rcgit-15+982+next+201610270632~ubuntu14.04.1
remmina-plugin-vnc                                    1.2.0~rcgit-15+982+next+201610270632~ubuntu14.04.1
libfreerdp-cache1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-client1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-codec1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-common1.1.0:amd64                          1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-core1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-crypto1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-gdi1.1:amd64                               1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-locale1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-plugins-standard:amd64                     2.0.0~dev201609090916+dfsg-1ubuntu0~git1855e36~trusty
libfreerdp-primitives1.1:amd64                        1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp-utils1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1           
libfreerdp1:amd64                                     2.0.0~dev201609090916+dfsg-1ubuntu0~git1855e36~trusty
remmina-plugin-rdp                                    1.2.0~rcgit-15+982+next+201610270632~ubuntu14.04.1   

  

RDP Server is:
  Windows Server 2012 R2 Standard

To reproduce(not 100% reproducible):
1. Start remmina
2. Connect to RDP server
3. Enter password wrong.
4. Connect to RDP server
5. Enter correct password.
9. Remmina Crashes.

```
(gdb) bt full
#0  0x00007fffdcc8917a in SetEvent () from /usr/lib/x86_64-linux-gnu/libwinpr.so.2
No symbol table info available.
#1  0x00007fffdcf74dbf in ?? () from /usr/lib/x86_64-linux-gnu/libfreerdp-client.so.2
No symbol table info available.
#2  0x00007fffdccc53b6 in ?? () from /usr/lib/x86_64-linux-gnu/libwinpr.so.2
No symbol table info available.
#3  0x00007ffff399570a in start_thread (arg=0x7fffcca5f700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffcca5f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736626816768, -4368985229558670498, 0, 140736683041823, 140736626817472, 0, 4368956041358613342, 4369010772565564254}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007ffff297082d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb) 
```

And again:

```
(gdb) run
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe00e6700 (LWP 11485)]
[New Thread 0x7fffdf8e5700 (LWP 11486)]
[New Thread 0x7fffdeed7700 (LWP 11487)]
[New Thread 0x7fffcffff700 (LWP 11488)]

(remmina:11481): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
[New Thread 0x7fffcef1b700 (LWP 11489)]
[Thread 0x7fffcffff700 (LWP 11488) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffcffff700 (LWP 11493)]
[12:22:14:294] [11481:11493] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[Thread 0x7fffcef1b700 (LWP 11489) exited]
[12:22:26:344] [11481:11493] [ERROR][com.freerdp.core.nla] - SPNEGO failed with NTSTATUS: C000006D
[12:22:26:344] [11481:11493] [ERROR][com.freerdp.core] - freerdp_set_last_error Unknown error class [0xC000006D]
[12:22:26:344] [11481:11493] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[12:22:26:344] [11481:11493] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[Thread 0x7fffcffff700 (LWP 11493) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffcef1b700 (LWP 11496)]
[12:22:30:705] [11481:11496] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[New Thread 0x7fffcda61700 (LWP 11497)]
[Thread 0x7fffcef1b700 (LWP 11496) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffcef1b700 (LWP 11499)]
[12:22:45:509] [11481:11499] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[12:22:51:873] [11481:11499] [ERROR][com.freerdp.core.nla] - SPNEGO failed with NTSTATUS: C000006D
[12:22:51:873] [11481:11499] [ERROR][com.freerdp.core] - freerdp_set_last_error Unknown error class [0xC000006D]
[12:22:51:873] [11481:11499] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[12:22:51:873] [11481:11499] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[Thread 0x7fffcef1b700 (LWP 11499) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffcd260700 (LWP 11504)]
[12:22:55:218] [11481:11504] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[New Thread 0x7fffcca5f700 (LWP 11505)]
[12:22:57:620] [11481:11505] [ERROR][com.freerdp.channels.cliprdr.client] - context->custom not set!
[12:22:57:620] [11481:11505] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_general_capability failed with error 1359!
[12:22:57:620] [11481:11505] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_clip_caps failed with error 1359!
[12:22:57:620] [11481:11505] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!
[Thread 0x7fffcca5f700 (LWP 11505) exited]

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

(remmina:11481): Gtk-CRITICAL **: _gtk_css_number_value_get: assertion 'number->class == &GTK_CSS_VALUE_NUMBER' failed

Thread 1 "remmina" received signal SIGSEGV, Segmentation fault.
0x00007ffff7615d60 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) bt full
#0  0x00007ffff7615d60 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#1  0x00007ffff7730fa9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#2  0x00007ffff772f200 in gtk_render_background () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#3  0x00007ffff77f50af in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#4  0x00007ffff7805937 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#5  0x00007ffff7805d37 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x00007ffff7805f22 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#7  0x00007ffff75fd25b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#8  0x00007ffff7601962 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#9  0x00007ffff7644dfc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#10 0x00007ffff7805937 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#11 0x00007ffff7805d37 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#12 0x00007ffff7805f22 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#13 0x00007ffff75fd25b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#14 0x00007ffff76e9472 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#15 0x00007ffff7805937 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#16 0x00007ffff7805f43 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#17 0x00007ffff75fd25b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#18 0x00007ffff7601962 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#19 0x00007ffff7805937 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#20 0x00007ffff7805f43 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#21 0x00007ffff75fd25b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#22 0x00007ffff7601962 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#23 0x00007ffff7810859 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#24 0x00007ffff7805937 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#25 0x00007ffff7805d37 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#26 0x00007ffff7805f22 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#27 0x00007ffff780616b in gtk_widget_send_expose () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#28 0x00007ffff76ba052 in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#29 0x00007ffff720ac18 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#30 0x00007ffff720bd3c in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#31 0x00007ffff720bef3 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#32 0x00007ffff68f11d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#33 0x00007ffff690b9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#34 0x00007ffff690c555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#35 0x00007ffff7204ed7 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#36 0x00007ffff71f42d8 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#37 0x00007ffff6f06ac3 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#38 0x00007ffff6f0605a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#39 0x00007ffff6f06400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#40 0x00007ffff6f064ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#41 0x00007ffff6be1cdd in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#42 0x0000000000418593 in main ()
No symbol table info available.
(gdb) 
(gdb) quit
```

And one more:

```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffccfde700 (LWP 11746)]
[12:34:02:911] [11720:11746] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[New Thread 0x7fffbbfff700 (LWP 11747)]
[12:34:05:844] [11720:11747] [ERROR][com.freerdp.channels.cliprdr.client] - context->custom not set!
[12:34:05:844] [11720:11747] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_general_capability failed with error 1359!
[12:34:05:844] [11720:11747] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_clip_caps failed with error 1359!
[12:34:05:844] [11720:11747] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!

Thread 14 "remmina" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbbfff700 (LWP 11747)]
__strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:94
94	../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt full
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:94
No locals.
#1  0x00007fffdd22b351 in setChannelError () from /usr/lib/x86_64-linux-gnu/libfreerdp.so.2
No symbol table info available.
#2  0x00007fffdcf74dbf in ?? () from /usr/lib/x86_64-linux-gnu/libfreerdp-client.so.2
No symbol table info available.
#3  0x00007fffdccc53b6 in ?? () from /usr/lib/x86_64-linux-gnu/libwinpr.so.2
No symbol table info available.
#4  0x00007ffff399570a in start_thread (arg=0x7fffbbfff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffbbfff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736347502336, 1275758499809784708, 0, 140736632575007, 140736347503040, 0, -1275908032729386108, -1275784601699945596}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff297082d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb) quit
```

Here are other steps that may end in a crash:  Also not 100% reproducible. 
1. Start remmina
2. Connect to RDP server
3. Enter password wrong.
4. Connect to RDP server
5. Enter correct password.
6. Get a screen over RDP that says "Connection in progress. Attempt X of 20.." where X switches between 0 and 1.
7. Close RDP session.
8. Connect to RDP server and authenticate correctly.
9. Remmina Crashes.

Ubuntu Apport crash report less the core dump:
https://gist.github.com/wsgcsysadmin/0c412d1ce7abe7fce6583c23d257d65b

Config file for connection:.`
```
[remmina]
ssh_server=
sound=off
sharefolder=
clientkey=
name=2x/admin
clientcert=
console=0
ssh_enabled=0
showcursor=false
exec=
clientname=
bitmapcaching=false
server=2x
colordepth=16
keyboard_grab=0
ssh_auth=0
scale=1
group=Servers
cacert=
quality=9
username=administrator
ssh_charset=
gkeymap=
aspectscale=false
password=
listenport=5500
hscale=0
execpath=
viewmode=4
window_maximize=1
viewonly=false
ssh_loopback=0
resolution=
domain=
ssh_username=
keymap=en-us
compression=false
window_height=848
security=
window_width=1418
toolbar_opacity=0
once=false
cacrl=
protocol=RDP
shareprinter=0
arguments=
disableserverinput=false
disableclipboard=0
vscale=0
ssh_privatekey=
loadbalanceinfo=
gateway_server=
sharesmartcard=0
cert_ignore=0
gateway_usage=0
precommand=
disablepasswordstoring=0
```

**Comment by giox069** [comment]
@wsgcsysadmin do you still have this issue in remmina 1.2.0-rcgit.20 ?

**Comment by wsgcsysadmin** [comment]
I have not had the problem for quite some time now. Thanks.
