### ISSUE TITLE
Remmina SEGV when shring desktop using pidgin-sipe

### ISSUE THREAD

**Issue by joakim-tjernlund** [FreeRDP/Remmina#1107]
Having latest remmina/freerdp(git) and shaing desktop via pidgin-sipe cause a SEGV in remmina:
remmina[9581]: segfault at 2aa2320 ip 00007fe21c655436 sp 00007fe1f917d578 error 6 in libc-2.23.so[7fe21c52e000+195000]

but just in one direction, sharing from my Desktop to Laptop, then remmina in my laptop starts and you
make out a black window before it SEGV.
if I use xfreerdp as viewer it works in my laptop.

Sharing from laptop to Desktop works.

**Comment by joakim-tjernlund** [comment]
Got a backtrace, thanks Jakub fpr the hint
```
[Switching to Thread 0x7fffd1e9c700 (LWP 2211)]
__memcpy_avx_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:204
204     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such
file or directory.
(gdb) bt full
#0  __memcpy_avx_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:204
No locals.
#1  0x00007fffe83d1d98 in freerdp_image_copy ()
   from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#2  0x00007fffe83efe59 in rfx_process_message ()
   from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#3  0x00007fffe8352a87 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#4  0x00007fffe83af2b5 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#5  0x00007fffe83acf47 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#6  0x00007fffe83ae3bd in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#7  0x00007fffe83a8657 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#8  0x00007fffe83a90fb in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#9  0x00007fffe83b13b9 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#10 0x00007fffe83a9678 in ?? () from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#11 0x00007fffe838d379 in freerdp_check_fds () from
/usr/lib64/libfreerdp2.so.2
No symbol table info available.
#12 0x00007fffe838e0ac in freerdp_check_event_handles ()
   from /usr/lib64/libfreerdp2.so.2
No symbol table info available.
#13 0x00007fffe8671abf in ?? ()
   from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
No symbol table info available.
#14 0x00007fffe867229a in ?? ()
   from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
No symbol table info available.
#15 0x00007ffff5b604a4 in start_thread (arg=0x7fffd1e9c700)
    at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd1e9c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736715147008, 
                -7535216358173484132, 0, 140737488340735, 0,
140736715147008, 
                7535132913350433692, 7535194842717051804}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007ffff533dfcd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

**Comment by joakim-tjernlund** [comment]
Better BT:
```
Thread 4 "remmina" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd1eb6700 (LWP 10142)]
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:204
204     ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) bt full
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:204
No locals.
#1  0x00007fffe83d6198 in memcpy (__len=256, __src=<optimized out>, __dest=0x13a2c00) at /usr/include/bits/string3.h:53
No locals.
#2  freerdp_image_copy (
    pDstData=pDstData@entry=0xb98000 "\200\203\206\377\200\203\206\377\201\203\205\377\201\203\204\377\201\204\203\377~\203\206\377z\201\210\377}\202\205\377\200\202\202\377\201\203\206\377\202\203\213\377\177\202\205\377}\201\200\377|\203\206\377{\205\214\377~\204\210\377\200\203\204\377\200\203\204\377\200\202\205\377\200\202\205\377\201\202\206\377\200\202\205\377\200\203\205\377\200\203\205\377\200\204\204\377\200\204\204\377\200\204\204\377\201\204\204\377\201\203\205\377\201\203\205\377\201\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377"..., DstFormat=DstFormat@entry=537168008, nDstStep=nDstStep@entry=7680, nXDst=<optimized out>, nYDst=<optimized out>, nWidth=64, 
    nHeight=64, pSrcData=0x7fffcc860740 '\377' <repeats 200 times>..., SrcFormat=537135240, nSrcStep=256, nXSrc=0, nYSrc=0, palette=0x0, flags=0) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/codec/color.c:523
        srcLine = <optimized out>
        dstLine = 0x13a2c00 <error: Cannot access memory at address 0x13a2c00>
        y = 10
        copyDstWidth = <optimized out>
        xSrcOffset = 0
        xDstOffset = <optimized out>
        vSrcVFlip = 0
        srcVOffset = <optimized out>
        srcVMultiplier = <optimized out>
#3  0x00007fffe83f41b1 in rfx_process_message (context=<optimized out>, data=<optimized out>, length=<optimized out>, left=<optimized out>, top=<optimized out>, 
    dst=0xb98000 "\200\203\206\377\200\203\206\377\201\203\205\377\201\203\204\377\201\204\203\377~\203\206\377z\201\210\377}\202\205\377\200\202\202\377\201\203\206\377\202\203\213\377\177\202\205\377}\201\200\377|\203\206\377{\205\214\377~\204\210\377\200\203\204\377\200\203\204\377\200\202\205\377\200\202\205\377\201\202\206\377\200\202\205\377\200\203\205\377\200\203\205\377\200\204\204\377\200\204\204\377\200\204\204\377\201\204\204\377\201\203\205\377\201\203\205\377\201\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377\202\203\205\377"..., dstFormat=537168008, dstStride=7680, dstHeight=1080, invalidRegion=0x0)
    at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/codec/rfx.c:1188
        nYSrc = <optimized out>
        nWidth = <optimized out>
        nHeight = <optimized out>
        stride = 256
        nXDst = <optimized out>
        nYDst = <optimized out>
        nXSrc = <optimized out>
        updateRect = {left = 0, top = 1088, right = 64, bottom = 1152}
        i = 510
        clippingRects = {extents = {left = 0, top = 0, right = 1920, bottom = 1200}, data = 0x7fffcc5c5390}
        j = 0
        nbUpdateRects = 1
        updateRects = 0x7fffcc4663f0
        pos = <optimized out>
        updateRegion = {extents = {left = 0, top = 1088, right = 64, bottom = 1152}, data = 0x7fffcc4663e0}
        blockLen = <optimized out>
        blockType = <optimized out>
        message = 0x7fffcc04cfe0
        s = <optimized out>
        ok = 1
        expectedDataBlockType = <optimized out>
        __FUNCTION__ = "rfx_process_message"
#4  0x00007fffe8361027 in gdi_surface_bits (context=0xa34550, cmd=0xa4c498) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/gdi/gdi.c:996
        format = <optimized out>
        gdi = 0x7fffcc026e60
        cmd = 0xa4c498
        context = 0xa34550
#5  0x00007fffe83b38e5 in update_recv_surfcmd_surface_bits (length=<synthetic pointer>, s=0x7fffcc04dad0, update=0xa4bfa0) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/surface.c:65
        pos = <optimized out>
        cmd = 0xa4c498
#6  update_recv_surfcmds (update=update@entry=0xa4bfa0, size=317212, size@entry=317222, s=s@entry=0x7fffcc04dad0) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/surface.c:108
        cmdType = 6
        cmdLength = <optimized out>
        __FUNCTION__ = "update_recv_surfcmds"
#7  0x00007fffe83b15f1 in fastpath_recv_update (fastpath=fastpath@entry=0xa54450, updateCode=updateCode@entry=4 '\004', size=size@entry=317222, s=0x7fffcc04dad0)
    at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/fastpath.c:289
        status = 0
        update = 0xa4bfa0
        context = 0xa34550
---Type <return> to continue, or q <return> to quit---
        pointer = 0xa4dd30
        __FUNCTION__ = "fastpath_recv_update"
#8  0x00007fffe83b29ed in fastpath_recv_update_data (s=0xa473c0, fastpath=0xa54450) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/fastpath.c:527
        next_pos = 6331
        cs = <optimized out>
        bulkStatus = <optimized out>
        totalSize = <optimized out>
        fragmentation = 1 '\001'
        transport = <optimized out>
        size = 6325
        rdp = <optimized out>
        compression = 0 '\000'
        compressionFlags = <optimized out>
        DstSize = 6325
        status = 0
        updateCode = 4 '\004'
        pDstData = 0x7e1806 "\265\362\b\025\257\220@\255|\202\005k\344\020+_ \201Z\371\004\n\327\310 V\276A"
#9  fastpath_recv_updates (fastpath=0xa54450, s=s@entry=0xa473c0) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/fastpath.c:563
        update = 0xa4bfa0
        __FUNCTION__ = "fastpath_recv_updates"
#10 0x00007fffe83acd57 in rdp_recv_fastpath_pdu (s=0xa473c0, rdp=0xa39530) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/rdp.c:1265
        length = 6328
        fastpath = 0xa54450
#11 rdp_recv_pdu (rdp=rdp@entry=0xa39530, s=s@entry=0xa473c0) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/rdp.c:1273
No locals.
#12 0x00007fffe83ad7fb in rdp_recv_callback (transport=<optimized out>, s=0xa473c0, extra=0xa39530) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/rdp.c:1419
        status = 0
        rdp = 0xa39530
        __FUNCTION__ = "rdp_recv_callback"
#13 0x00007fffe83b59e9 in transport_check_fds (transport=transport@entry=0xa47010) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/transport.c:904
        status = 6331
        recv_status = <optimized out>
        received = 0xa473c0
        now = <optimized out>
        dueDate = 22638151
        __FUNCTION__ = "transport_check_fds"
#14 0x00007fffe83add78 in rdp_check_fds (rdp=0xa39530) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/rdp.c:1478
        status = <optimized out>
        transport = 0xa47010
        __FUNCTION__ = "rdp_check_fds"
#15 0x00007fffe8399a89 in freerdp_check_fds (instance=0xa12000) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/freerdp.c:316
        status = <optimized out>
        rdp = <optimized out>
        __FUNCTION__ = "freerdp_check_fds"
#16 0x00007fffe839a7bc in freerdp_check_event_handles (context=0xa34550) at /var/tmp/portage/net-misc/freerdp-9999/work/freerdp-9999/libfreerdp/core/freerdp.c:365
        status = <optimized out>
        __FUNCTION__ = "freerdp_check_event_handles"
#17 0x00007fffe8671abf in remmina_rdp_main_loop (gp=0x6f4280) at /var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c:697
        status = <optimized out>
        handles = {0xa4b440, 0x7fffcc004c30, 0xb8d200, 0xb8bb40, 0xb8bb70, 0xb8fa00, 0x100000000, 0x7fffd1eb5ac0, 0x89288632, 0x7fffe866aa7c, 0xffffffff, 0x0, 0x7ffff5b5be90, 0x7ffff7fb89b8, 0x0 <repeats 11 times>, 
          0x7fffe887d3c8 <pthread_testcancel@got.plt>, 0x0, 0x7fffffffc6ff, 0x0, 0x7fffd1eb6700, 0x0, 0x7ffff7de7886 <_dl_fixup+214>, 0x5, 0x0, 0x0, 0x7ffff5b5be90, 0x7fffd1eb5d20, 0x7ffff7dee913 <_dl_runtime_resolve_avx+179>, 0x0, 
          0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x200000004, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x400000002, 0x7fffe867935e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x300000003, 0x0}
        buf = '\000' <repeats 88 times>, "\200Bo\000\000\000\000\000\000\000\000"
        rfi = 0xa34550
        nCount = <optimized out>
#18 remmina_rdp_main (gp=gp@entry=0x6f4280) at /var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c:1109
        s = <optimized out>
        value = <optimized out>
        rdpsnd_params = {0x5 <error: Cannot access memory at address 0x5>, 0x0, 0x1 <error: Cannot access memory at address 0x1>}
        rdpsnd_nparams = <optimized out>
        rdpsnd_param1 = '\000' <repeats 15 times>
        rdpsnd_param2 = '\000' <repeats 15 times>
        cs = <optimized out>
        remminafile = <optimized out>
---Type <return> to continue, or q <return> to quit---
        rfi = <optimized out>
        gateway_host = 0xb <error: Cannot access memory at address 0xb>
        gateway_port = -773104760
        desktopOrientation = 0
        desktopScaleFactor = 0
        deviceScaleFactor = 0
#19 0x00007fffe867229a in remmina_rdp_main_thread (data=0x6f4280) at /var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c:1125
        gp = 0x6f4280
        rfi = 0xa34550
#20 0x00007ffff5b604a4 in start_thread (arg=0x7fffd1eb6700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd1eb6700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736715253504, 7014975959418515230, 0, 140737488340735, 0, 140736715253504, -7015041821721252066, -7014963230563782882}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#21 0x00007ffff533dfcd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb)

**Comment by joakim-tjernlund** [comment]
Guys, head over to 
 https://github.com/FreeRDP/FreeRDP/issues/3749
the problem is identified but where to fix it isn't

**Comment by akallabeth** [comment]
@antenore @giox069 I've had a look at the RDP plugin and I've stumbled over some issues with your usage of GDI
* Since you use CAIRO it would be better to create the correctly aligned buffer with ```cairo_image_surface_create ()``` and use the buffer with ```gdi_init_ex``` so that the alignment requirements are always met
* Adjust your use of ```gdi_resize``` and replace with ```gdi_resize_ex```
* I don't get why are you creating a custom RFX context. Since you're using SoftwareGDI you only need to update the screen whenever end paint is called
* GFX modes, which you currently disabled, are a free addition when used like that.

Since you probably used xfreerdp as a template, better have a look at the android client which is more similar to your use case.

**Comment by giox069** [comment]
@akallabeth thank you, we will take a look with your suggestions. Unfortunately we are not fulltime programmers, so many times we miss something.
Yes, I have used and reverse-engineered xfreerdp a lot of times to build the remmina RDP plugin, I had no idea that rfx context was not necessary if we only use softwareGDI. I will take a loot at the android client.
Thank you again.

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @akallabeth @giox069 @joakim-tjernlund

**Comment by joakim-tjernlund** [comment]
how do one "link it to github" ?

**Comment by antenore** [comment]
@joakim-tjernlund 
Settings -> account -> Social sign-in -> Github icon
