### ISSUE TITLE
Provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [FreeRDP/Remmina#1123]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional(!) desktop integration with `appimaged`
- Binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Since this project is already using Travis CI to produce continuous builds, these could be bundled up as AppImages relatively easily, as [these projects](https://github.com/search?utf8=%E2%9C%93&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&ref=searchresults) already do.

**Comment by probonopd** [comment]
An example Remmina AppImage can be downloaded from
https://bintray.com/probono/AppImages/Remmina/_latestVersion#files

Since this was built from the binaries in the trusty ppa, it is expected to run on most 2014-ish and later distributions. It is expected that some fine-tuning may still be required.

**Comment by giox069** [comment]
@probonopd as mainstream developers, we cannot afford to be the maintainers of binary packages. So we usually delegate packaging to different people: Ubuntu's PPA, Ubuntu's snap, Fedora, OpenSuse, Arch.... Each binary package system has its own maintainer. 
We also usually leave the freedom to the package maintainer to do some modifications to the upstream code, via a pull request, for example for modifying cmake compilation rules or just to host some package specific files inside the Remmina code.
So, if you find someone interested in producing and maintaining AppImage packages (you?) for remmina, we will be happy to have it in the team :)
Please note that I used the term "maintaining": packaging is a medium/long commitment and requires that at least one person will be available to fix issues that will appear in the future.

**Comment by probonopd** [comment]
@giox069 would you be interested in having your Travis CI build products be bundled up as an AppImage automatically on each build, like [done here](https://github.com/search?utf8=%E2%9C%93&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&ref=searchresults)?

**Comment by ic3d** [comment]
@probonopd thanks for your help! 
@giox069 was very busy in the last days, but he said me that he accepts your kind offer. Thanks!

**Comment by probonopd** [comment]
Can't promise an ETA yet but will add this to my TODO list.

**Comment by giox069** [comment]
@probonopd, I'm asking your help after tests with TarvisCI and OBS in remmina issue #1248.
No one answered on how to ckecout a non master branch in OBS, so  I decided to write a build script, inspired by Recipe, which runs on debian8 an builds an AppImage. You can see it [here](https://github.com/giox069/remmina_appimage). It's in a temporary repository, I think I will move it inside the remmina project as soon as is works.
The script works an generates the AppImage files, but I have 2 problems during execution of the AppImage generated binary:
1. Executing in debian 9, tha AppImage imediately crashes with a segmentation fault, see stacktrace here:
```
giovanni@debian9:~/bin$ gdb ./Remmina-1.2.0_rcgit_20_8f13dff.glibc2.14-x86_64.AppImage 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Remmina-1.2.0_rcgit_20_8f13dff.glibc2.14-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/giovanni/bin/Remmina-1.2.0_rcgit_20_8f13dff.glibc2.14-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 1572 is executing new program: /tmp/.mount_Remmink0ruQa/AppRun
process 1572 is executing new program: /bin/bash

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7621bdf in __libc_start_main ()
   from /tmp/.mount_Remmink0ruQa/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7621bdf in __libc_start_main ()
   from /tmp/.mount_Remmink0ruQa/lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000042229a in _start ()
(gdb) 
```
Any idea ?
2. Executing under debian 8 fails, due to some hardcoded path in the executable. What am I missing in the script? I need to change those paths, I have seen some examples with sed, but it's not clear to me what the final path after sed should be.
```
(remmina:1227): Gtk-ERROR **: failed to add UI: Failed to open file '/root/remmina_AppImage/Remmina/Remmina.AppDir/usr/share/remmina/ui/remmina_main.glade': Permission denied
Rilevato trace/breakpoint
```

Thank you for all your help.

**Comment by probonopd** [comment]
> Executing in debian 9, tha AppImage imediately crashes with a segmentation fault, see stacktrace here

Please make sure that you do __not__ bundle any of the libraries from this list in your AppImage, and certainly not libc.so.6: https://github.com/AppImage/AppImages/blob/master/excludelist

> Executing under debian 8 fails, due to some hardcoded path in the executable

Most likely the source code needs to be changed to load the glade file from a location relative to the executable rather than from an absolute path in the compile-time PREFIX.

**Comment by giox069** [comment]
About lib dependencies of question 1: I was using delete_blacklisted before copy_deps, your hint helped me to find the error quickly. Thank you.
Now debian 9 says:
```
/tmp/.mount_Remminx3SlyU/usr/bin/remmina: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_buffer_set_cluster_level
```
In the meanwhile I rewrote delete_blacklisted to skip libpango* and it seems to work. Is ir correct ?

2nd question: I'm doing some changes to the code and Cmakefiles to have relocatable data paths, so I don't need to use sed to patch the binaries.

**Comment by probonopd** [comment]
Please see https://github.com/AppImage/AppImageKit/issues/454.

**Comment by probonopd** [comment]
Looks like AppImage is now being generated, but where can it be downloaded from?

**Comment by giox069** [comment]
Hi @probonopd ... appimage is still not ready. I temporarily aborted the project a couple of months ago due difficulties with GTK compatibility. Now unfortunately I'm very busy to fix other urgent issues.
I remember that I had the best results using my own scripts to build appimage (no Travis, no OBS), but I can't remember more useful info. One of the problem was with GTK and icon cache regeneration at runtime (which is blocked, because the AppImage directories are readonly... but unfortunately I can't remember well what I was doing.

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @giox069 @ic3d @probonopd

**Comment by probonopd** [comment]
Thanks @antenore. Will it be on the private instance https://gitlab.gnome.org/ like other GNOME apps or on the public https://gitlab.com?

**Comment by antenore** [comment]
Gitlab.com @probonopd
