### ISSUE TITLE
RDP: shared folders and clipboard doesn't work in 1.2.0-rcgit-26

### ISSUE THREAD

**Issue by QuAzI** [FreeRDP/Remmina#1429]
* Client (OS name and version): Linux Mint 17.3 KDE
* Remmina version (remmina --version): 
```
> remmina --version
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
Remmina - 1.2.0-rcgit-26 (git rcgit-26)
```
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): Windows 7, Windows Server 2008R2 and Windows Server 2016
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 
```
> xfreerdp --version
This is FreeRDP version 2.0.0-dev2 (n/a)
```

Application crashes (**and all opened connections too!**) when I try to choose shared folder
```
> remmina
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:18160): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(remmina:18160): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(remmina:18160): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(remmina:18160): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gtype.c:4210: type id '0' is invalid

(remmina:18160): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
```

Clipboard between client and server doesn't work too. Only local clipboard.

**Comment by antenore** [comment]
It looks like a GTK bug.

Can you install the debug package and rerun remmina with gdb? I need a back trace if you can.

Regarding the clipboard, can you test with xfreerdp from the command line?

If you have the possibility to rollback to rcgit.24 it would be good to validate whatever is a version issue.

Thanks

**Comment by QuAzI** [comment]
Debug output for Remmina - 1.2.0-rcgit-27 (git rcgit-27)
```
quazi@quazi-desktop:/storages/main/Installs/Qt-5.9.4 > gdb remmina
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from remmina...Reading symbols from /usr/lib/debug/.build-id/b0/ad63590230ed774933c13339778e7c963d1715.debug...done.
done.
(gdb) r
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecfd1700 (LWP 6291)]
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
[New Thread 0x7fffe0dfc700 (LWP 6292)]
[New Thread 0x7fffdbcfb700 (LWP 6295)]

(remmina:6286): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(remmina:6286): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
[New Thread 0x7fffc684f700 (LWP 6300)]
[New Thread 0x7fffc604e700 (LWP 6301)]
[Thread 0x7fffe0dfc700 (LWP 6292) exited]
[New Thread 0x7fffe0dfc700 (LWP 6306)]
[Thread 0x7fffc684f700 (LWP 6300) exited]

(remmina:6286): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(remmina:6286): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gtype.c:4210: type id '0' is invalid

(remmina:6286): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff795ce45 in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
```

**Comment by giox069** [comment]
@QuAzI: just one extra step: can you get a backtrace? When you are inside gdb, after the crash, just type ``bt`` and copy the output here.

**Comment by QuAzI** [comment]
I try to select "File system" to select directory.

![image](https://user-images.githubusercontent.com/1897605/36296172-03aaa1ac-12fd-11e8-8e7a-b1b35fa336bf.png)

```
(gdb) r
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecfd1700 (LWP 21259)]
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
[New Thread 0x7fffe0dfc700 (LWP 21260)]
[New Thread 0x7fffdbcfb700 (LWP 21263)]

(remmina:21255): Gtk-WARNING **: /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(remmina:21255): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
[Thread 0x7fffe0dfc700 (LWP 21260) exited]
[New Thread 0x7fffe0dfc700 (LWP 21632)]
[New Thread 0x7fffc684f700 (LWP 21633)]
[New Thread 0x7fffc604e700 (LWP 21634)]
[Thread 0x7fffc684f700 (LWP 21633) exited]
[New Thread 0x7fffc684f700 (LWP 21640)]
[Thread 0x7fffe0dfc700 (LWP 21632) exited]

(remmina:21255): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(remmina:21255): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gtype.c:4210: type id '0' is invalid

(remmina:21255): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff795ce45 in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff795ce45 in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#1  0x00007ffff795d15c in gtk_tree_model_get () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff7814c20 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff77cb9f5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff77d0e42 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff786ac7c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff6b663b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff6b77d3d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff6b7f6f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6b7fce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7993c64 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff78690bc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff786a94a in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff746ec32 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007ffff7162e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff7163048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff71630ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff6e49b9c in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x000000000041a2a7 in main (argc=1, argv=0x7fffffffdb58)
    at /build/remmina-encVQu/remmina-1.2.0-rcgit-27/remmina/src/remmina.c:261
```

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @antenore @giox069 @QuAzI
