### ISSUE TITLE
crashes in ssh_channel_close in libssh

### ISSUE THREAD

**Issue by ignatenkobrain** [FreeRDP/Remmina#217]
Steps to reproduce:
1. Connect to ssh server
2. Disconnect (Ctrl+D)
3. Connect to rdp server over ssh tunnel
4. Disconnect (button)

```
Program received signal SIGSEGV, Segmentation fault.
ssh_channel_close (channel=0x7fffd800bf70)
    at /usr/src/debug/libssh-0.5.4/src/channels.c:1092
1092      enter_function();
```
# Backtrace

```
#0  ssh_channel_close (channel=0x7fffd800bf70) at /usr/src/debug/libssh-0.5.4/src/channels.c:1092
#1  0x00007ffff7dbf3d5 in channel_close (channel=<optimized out>) at /usr/src/debug/libssh-0.5.4/src/legacy.c:59
#2  0x000000000043947d in remmina_ssh_tunnel_close_all_channels (tunnel=tunnel@entry=0x7fffd00008e0) at /usr/src/debug/FreeRDP-Remmina-356c033/remmina/src/remmina_ssh.c:596
#3  0x000000000043b423 in remmina_ssh_tunnel_free (tunnel=0x7fffd00008e0) at /usr/src/debug/FreeRDP-Remmina-356c033/remmina/src/remmina_ssh.c:1209
#4  0x0000000000432a37 in remmina_protocol_widget_close_connection (gp=0x9d6360) at /usr/src/debug/FreeRDP-Remmina-356c033/remmina/src/remmina_protocol_widget.c:283
#5  0x0000003ac160fc57 in _g_closure_invoke_va (closure=closure@entry=0xacdfb0, return_value=return_value@entry=0x0, instance=instance@entry=0xa391a0, args=args@entry=0x7fffffffd2a0, n_params=0, param_types=0x0) at gclosure.c:840
#6  0x0000003ac1627d87 in g_signal_emit_valist (instance=instance@entry=0xa391a0, signal_id=signal_id@entry=247, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffd2a0) at gsignal.c:3234
#7  0x0000003ac1628fa2 in g_signal_emit_by_name (instance=0xa391a0, detailed_signal=0x32c532a788 "clicked") at gsignal.c:3424
```

We are using in libssh:

``` c
if (channel == NULL) {
  return SSH_ERROR;
}
```

from gdb

```
(gdb) print channel
$1 = (struct ssh_channel_struct *) 0x7fffd800bf70
(gdb) print channel->session
$2 = (ssh_session) 0x0
```
##

**Comment by ic3d** [comment]
Hi @ignatenkobrain do you still get this issue with the latest version of Remmina? 
Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it affects an old version of Remmina - we only support Remmina 1.2.* branch.
