### ISSUE TITLE
Segfault in rf_Pointer_Free of rdp plugin

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#269]
Master branch freerdp (94a836078f075a56753b9495d897a666095808e7), master branch of Remmina (26b814aec6e930746d079c885449dd50d3484fb0).

On try connect to Windows server:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9a86700 (LWP 30904)]
0x00007ffff0b3ba28 in rf_Pointer_Free () from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
(gdb) bt
#0  0x00007ffff0b3ba28 in rf_Pointer_Free () from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
#1  0x000000354ca41a1c in Pointer_Free () from /lib64/libfreerdp-core.so.1.2
#2  0x000000354f603a03 in pointer_cache_put () from /lib64/libfreerdp-cache.so.1.2
#3  0x000000354f603bc3 in update_pointer_new () from /lib64/libfreerdp-cache.so.1.2
#4  0x000000354ca52a5b in fastpath_recv_update.isra () from /lib64/libfreerdp-core.so.1.2
#5  0x000000354ca5306e in fastpath_recv_updates () from /lib64/libfreerdp-core.so.1.2
#6  0x000000354ca518dd in rdp_recv_pdu () from /lib64/libfreerdp-core.so.1.2
#7  0x000000354ca55a9d in transport_check_fds () from /lib64/libfreerdp-core.so.1.2
#8  0x000000354ca51d6d in rdp_check_fds () from /lib64/libfreerdp-core.so.1.2
#9  0x000000354ca40fe7 in freerdp_check_fds () from /lib64/libfreerdp-core.so.1.2
#10 0x00007ffff0b36f3f in remmina_rdp_main_loop () from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
#11 0x00007ffff0b37468 in remmina_rdp_main_thread () from /usr/lib64/remmina/plugins/remmina-plugin-rdp.so
#12 0x0000003d00a07f33 in start_thread (arg=0x7fffe9a86700) at pthread_create.c:309
#13 0x0000003cffef4ded in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Hubbitus** [comment]
I think it may be closed. Thank you very much.
