### ISSUE TITLE
Remmina crashes taking a screenshot

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#803]
The screenshot path is set to NULL.

```
(gdb) bt
#0  0x00007ffff6be7850 in ?? () from 
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#1  0x00007ffff6bf24a3 in ?? () from 
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007ffff6be53d0 in g_application_send_notification () from 
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x000000000043a2b3 in remmina_public_send_notification ()
#4  0x000000000041ed6a in ?? ()
#5  0x00007ffff68f41d4 in ?? () from 
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
```

The coming commit should fix this

**Comment by antenore** [comment]
@giox069 this is the first fix, it should be enough for the above crash
