### ISSUE TITLE
Screenshot crash under Ubuntu 16.04

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#836]
Latest version of remmina, running on Ubuntu 16.40 x64 desktop. Connected to Windows 7.
Pressing the "screenshot" button on the toolbar, makes remmina crash.
Here is the backtrace:
```
Thread 1 "remmina" received signal SIGSEGV, Segmentation fault.
g_application_impl_get_dbus_connection (impl=0x0)
    at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gapplicationimpl-dbus.c:785
785	/build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gapplicationimpl-dbus.c: File o directory non esistente.
(gdb) bt
#0  0x00007ffff6be4950 in g_application_impl_get_dbus_connection (impl=0x0)
    at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gapplicationimpl-dbus.c:785
#1  0x00007ffff6be0f0a in g_application_get_dbus_connection (application=application@entry=0x6f0220 [GApplication]) at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gapplication.c:1942
#2  0x00007ffff6bef5a3 in g_notification_backend_new_default (application=application@entry=0x6f0220 [GApplication]) at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gnotificationbackend.c:58
#3  0x00007ffff6be24d0 in g_application_send_notification (application=0x6f0220 [GApplication], id=0x456530 "remmina-screenshot-is-ready-id", notification=0x83e8a0 [GNotification])
    at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gio/gapplication.c:2753
#4  0x000000000043a958 in remmina_public_send_notification (notification_id=0x456530 "remmina-screenshot-is-ready-id", notification_title=0x45651a "Screenshot taken", notification_message=0xb78130 "/home/giovanni/Immagini/1461100667597.remmina-2016-4-19-21:22:26,294381.png")
    at /home/giovanni/remmina_devel/Remmina/remmina/src/remmina_public.c:680
#5  0x000000000044ab2a in remmina_connection_holder_toolbar_screenshot (widget=0x953500 [GtkToolButton], cnnhld=0xabb330) at /home/giovanni/remmina_devel/Remmina/remmina/src/remmina_connection_window.c:1668
#6  0x00007ffff68f11d4 in _g_closure_invoke_va (closure=closure@entry=0xabeb10, return_value=return_value@entry=0x0, instance=instance@entry=0x953500, args=args@entry=0x7fffffffc568, n_params=<optimized out>, param_types=0x0) at /build/glib2.0-t9oPgV/glib2.0-2.48.0/./gobject/gclosure.c:867
```

**Comment by antenore** [comment]
Also on Arch Linux, but I suspect that it happens on any new/fresh/clean installation of Remmina.

Try to set the screenshot folder in the remmina preferences.

**Comment by antenore** [comment]
Wel... not on Fedora at least... I've removed the properties by hand (vim) in the remmina.properties and I cannot reproduce the issue.

So it's really something related to the new GTK/Glib

**Comment by antenore** [comment]
This commit doesn't solve the issue, it's just something related that is better to fix in the same context I think.
