### ISSUE TITLE
Segmentation Fault on FreeBSD using SPICE

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#876]
See PR #874 

* Client (OS name and version):  FreeBSD 10.3
* Remmina version (remmina --version): Last git commit
* Desktop environment (GNOME, Unity, KDE, ..): i3wm
* Connecting to (OS and version): Ubuntu 16.04 LTS
* Connecting via (RDP, VNC, ...): SPICE

https://github.com/FreeRDP/Remmina/files/278402/gdb.txt

**Comment by antenore** [comment]
It's seems it's a confélict between OpenSSL and LibreSSL, here some addtitional logs:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000808dae79c in strcmp () from /lib/libc.so.7
(gdb) bt
#0  0x0000000808dae79c in strcmp () from /lib/libc.so.7
#1  0x000000081096cd3b in lh_insert () from /lib/libcrypto.so.7
#2  0x0000000810974568 in OBJ_NAME_add () from /lib/libcrypto.so.7
#3  0x0000000810973f4b in EVP_add_digest () from /lib/libcrypto.so.7
#4  0x000000081ade8e04 in SSL_library_init () from /usr/local/lib/libssl.so.38
#5  0x000000081a8690a4 in spice_channel_class_init (klass=0x818927ac0) at spice-channel.c:363
#6  spice_channel_class_intern_init (klass=0x818927ac0) at spice-channel.c:78
#7  0x0000000801bd2cd5 in g_type_class_ref () from /usr/local/lib/libgobject-2.0.so.0
#8  0x0000000801bd28af in g_type_class_ref () from /usr/local/lib/libgobject-2.0.so.0
#9  0x0000000801bc040a in g_object_new_valist () from /usr/local/lib/libgobject-2.0.so.0
#10 0x0000000801bc0110 in g_object_new () from /usr/local/lib/libgobject-2.0.so.0
#11 0x000000081a86ba8a in spice_channel_new (s=0x81a1fa180, type=1, id=0) at spice-channel.c:2157
#12 0x000000081a866d52 in spice_session_connect (session=0x81a1fa180) at spice session.c:1568
```

Valgrind:
```
==69683== 1 errors in context 1 of 3602:
==69683== Invalid read of size 1
==69683==    at 0x4C25F11: strcmp (in /usr/local/lib/valgrind/vgpreload_memcheck-amd64-freebsd.so)
==69683==    by 0x14C76D3A: lh_insert (in /lib/libcrypto.so.7)
==69683==    by 0x14C7E567: OBJ_NAME_add (in /lib/libcrypto.so.7)
==69683==    by 0x14C7DF4A: EVP_add_digest (in /lib/libcrypto.so.7)
==69683==    by 0x1F2647C1: SSL_library_init (ssl_algs.c:124)
==69683==    by 0x1ECD50A3: spice_channel_class_init (spice-channel.c:363)
==69683==    by 0x1ECD50A3: ??? (spice-channel.c:78)
==69683==    by 0x5FFCCD4: g_type_class_ref (in /usr/local/lib/libgobject-2.0.so.0.4600.2)
==69683==    by 0x5FFC8AE: g_type_class_ref (in /usr/local/lib/libgobject-2.0.so.0.4600.2)
==69683==    by 0x5FEA409: g_object_new_valist (in /usr/local/lib/libgobject-2.0.so.0.4600.2)
==69683==    by 0x5FEA10F: g_object_new (in /usr/local/lib/libgobject-2.0.so.0.4600.2)
==69683==    by 0x1ECD7A89: spice_channel_new (spice-channel.c:2157)
==69683==    by 0x1ECD2D51: spice_session_connect (spice-session.c:1568)
==69683==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==69683==
```

**Comment by larchunix** [comment]
Hmm, I don't have any clue to fix this.

**Comment by antenore** [comment]
Yeah don't worry. It's more like I'm keeping a log.

**Comment by antenore** [comment]
Fixed moving back to vanilla FreeBSD. It's something with PC-BSD

**Comment by larchunix** [comment]
Good news !
